# Generated by Django 5.2.1 on 2025-10-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositoAmpollas',
            fields=[
                ('idAmpolla', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMedicamento', models.TextField(max_length=255)),
                ('lote', models.CharField(max_length=255)),
                ('vencimiento', models.DateField()),
                ('laboratorio', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('stockCritico', models.IntegerField(max_length=255)),
                ('cantidadStock', models.IntegerField(max_length=255)),
                ('cantDispensada', models.IntegerField(max_length=255)),
                ('cantIngresada', models.IntegerField(max_length=255)),
                ('SaldoMensual', models.IntegerField(max_length=255)),
            ],
        ),
    ]
